#!/bin/bash

# List of unused files
files=(
"src/components/AIInputPanel.tsx"
"src/components/AssetBrowser.jsx"
"src/components/AssetGallery.tsx"
"src/components/AssetGallery.css"
"src/components/AssetInspector.tsx"
"src/components/MasteryMap.tsx"
"src/components/PhysicsOverlay.jsx"
"src/components/PromptBar.jsx"
"src/components/PropertiesPanel.jsx"
"src/components/SimulationCanvas.tsx"
"src/components/SimulationToolbar.jsx"
"src/components/analytics/AnalyticsCard.tsx"
"src/components/formula-lab/AIInsightPanel.tsx"
"src/components/formula-lab/FormulaNavigator.tsx"
"src/components/formula-lab/PracticeQuestions.tsx"
"src/components/formula-lab/RelationshipVisualizer.tsx"
"src/components/formula-lab/RevisionCards.tsx"
"src/components/formula-lab/WorkedExamples.tsx"
"src/components/layout/EmptyState.tsx"
"src/components/layout/FloatingButton.tsx"
"src/components/layout/PageTransition.tsx"
"src/components/sim/laws/FirstLawCanvas.tsx"
"src/components/sim/laws/LawControls.tsx"
"src/components/sim/laws/LawGraphPanel.tsx"
"src/components/sim/laws/SecondLawCanvas.tsx"
"src/components/sim/laws/ThirdLawCanvas.tsx"
"src/components/tutor/PremiumTutorMarkdownRenderer.tsx"
"src/components/tutor/TextbookResourcesPanel.tsx"
"src/components/tutor/TutorInputPanel.tsx"
"src/components/tutor/structured/TopicPageRenderer.tsx"
"src/components/ui/MarkdownMath.tsx"
"src/components/ui/accordion.tsx"
"src/components/ui/alert-dialog.tsx"
"src/components/ui/aspect-ratio.tsx"
"src/components/ui/breadcrumb.tsx"
"src/components/ui/calendar.tsx"
"src/components/ui/carousel.tsx"
"src/components/ui/command.tsx"
"src/components/ui/context-menu.tsx"
"src/components/ui/drawer.tsx"
"src/components/ui/dropdown-menu.tsx"
"src/components/ui/hover-card.tsx"
"src/components/ui/input-otp.tsx"
"src/components/ui/menubar.tsx"
"src/components/ui/navigation-menu.tsx"
"src/components/ui/pagination.tsx"
"src/components/ui/radio-group.tsx"
"src/components/ui/resizable.tsx"
"src/components/ui/scroll-area.tsx"
"src/components/ui/toggle-group.tsx"
"src/data/animations.js"
"src/data/generateAssetIndex.js"
"src/data/mockData.ts"
"src/data/searchIndex.json"
"src/hooks/useLawLabAnalytics.ts"
"src/sandbox/components/AssistedModePanel.tsx"
"src/sandbox/components/ChallengePanel.tsx"
"src/sandbox/hooks/useAssetRegistry.ts"
"src/sandbox/intelligence/topicInference.ts"
"src/sandbox/properties/gravity/gravity.defaults.ts"
"src/sandbox/properties/gravity/gravityProperties.ts"
"src/sandbox/properties/gravity/planetProperties.ts"
"src/services/simulationSynthesisService.ts"
"src/svgs/planets/Mooon.svg"
"src/svgs/vehicles/car_1.svg"
"src/svgs/vehicles/rocket_1.svg"
"src/svgs/vehicles/truck_1.svg"
"src/utils/AssetResolver.js"
"src/utils/DynamicQuestionGenerator.ts"
"src/utils/assetCatalogResolver.js"
"src/utils/imageSafeLoader.ts"
)

# Loop and move
for file in "${files[@]}"; do
  if [ -f "$file" ]; then
    # Target directory under scratch
    dest_dir="scratch/$(dirname "$file")"
    mkdir -p "$dest_dir"
    git mv "$file" "$dest_dir/"
    echo "Moved: $file -> $dest_dir/"
  else
    echo "Skipping (not found): $file"
  fi
done
